Add change to readme to map tflint.d directory so we can init
terraform-linters/tflint pull request #1309
Opened 2022-02-08 16:06 UTC by babyhuey

If we don't do this, then it is more difficult to run init and then run tflint. This maps that so that it gets added to your home directory so all projects can use the initialized tflint

2022-02-08 16:31 UTC, bendrucker requested changes
This might be the right choice for you but it's not necessarily a suitable default. Relying on host mounts to share data across commands run in different containers is viable but not ideal. 

We'd accept an example of how to run multiple commands in a single container via a shell if you'd like to add one.

2022-02-08 16:44 UTC, babyhuey commented
Out of curiosity, what is your current recommended way of doing an init inside of the container? Up to the user to map/figure out?

2022-02-08 16:46 UTC, babyhuey commented
Or what about changing the entrypoint to automatically run the init?

2022-03-27 07:59 UTC, wata727 commented
I think there is room for improvement in the Docker image as a pluggable linter. The current usage is designed for TFLint running as a single binary and may not be suitable for the current architecture. However, I haven't thought about what to do yet.

2022-05-10 19:27 UTC, closed without merging